### ISSUE TITLE
Shipping dimensions 

### ISSUE THREAD

**Issue by xcsrz** [mrmikemon/spree_aus_post_shipping#2]
The readme states "The Calculator will sum up any dimensions or weight information from order line items."  However, I don't see this happening with dimensions and the code is hard wired to take the values from the default dimensions.

**Comment by mrmikemon** [comment]
Hi,

You are quite correct. My customer wasn't populating dimension or weight information so it remained untested.

Happy to accept a pull request to correct it.

**Comment by xcsrz** [comment]
I'm working on 2-2 compatibility in my fork.  I'd like to get it to the point where it takes in box sizes and figures out what size box to fit all the products.  That's pretty far off at this point.  Right now I've got it to where it makes individual API calls for each product (current reqs for my immediate needs) and sums the postage of all those shipment calculations.
