### ISSUE TITLE
Error: We are unable to calculate shipping rates for the selected items

### ISSUE THREAD

**Issue by renshah** [mrmikemon/spree_aus_post_shipping#3]
I am getting below error. Can anyone tell me whats wrong?

We are unable to calculate shipping rates for the selected items.

**Comment by mrmikemon** [comment]
Have you obtained and API key from AusPost?
Also check that you've set up all the default settings for average parcel size and weight.

**Comment by mrmikemon** [comment]
Closing - assuming issue corrected.
